# Generated by Django 3.1.4 on 2020-12-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_auto_20201228_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(max_length=8),
        ),
    ]
