# Generated by Django 3.1.4 on 2020-12-31 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0004_useraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
