# Generated by Django 3.1.4 on 2021-02-17 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0002_auto_20210217_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='review_detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='ProductReviews'),
        ),
    ]
