# Generated by Django 3.1.4 on 2021-02-08 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0003_auto_20210208_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.RemoveField(
            model_name='review',
            name='content',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product_rate',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_user',
        ),
        migrations.RemoveField(
            model_name='reviewimage',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewimage',
            name='review_detail_image',
        ),
    ]
