# Generated by Django 3.1.4 on 2021-02-08 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0004_auto_20210208_1446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='ReviewImage',
        ),
    ]
