# Generated by Django 3.1.4 on 2021-02-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0006_review_reviewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product_rate',
            field=models.PositiveIntegerField(),
        ),
    ]
