# Generated by Django 3.1.4 on 2021-01-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressapp', '0003_useraddress_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='is_default',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
