# Generated by Django 3.1.4 on 2021-01-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressapp', '0004_auto_20210112_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
