# Generated by Django 3.1.4 on 2021-01-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressapp', '0005_auto_20210112_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='address_detail_info',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
