# Generated by Django 3.1.4 on 2021-01-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressapp', '0006_useraddress_address_detail_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_detail_info',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
