# Generated by Django 3.1.4 on 2021-01-16 15:31

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('product_code', models.CharField(max_length=10, unique=True)),
                ('product_sale_id', models.CharField(max_length=10, unique=True)),
                ('product_title', models.CharField(max_length=100)),
                ('product_origin_price', models.IntegerField()),
                ('product_sale_price', models.IntegerField()),
                ('product_description', models.CharField(max_length=200)),
                ('product_is_display', models.BooleanField(default=True)),
                ('product_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductThumbnailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='product_thumbnails')),
                ('p_target_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_thumbnails', to='productapp.product', verbose_name='p_target_product_id')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOptionParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_target_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='productapp.product', verbose_name='p_target_product_id')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOptionChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_option_child_title', models.CharField(max_length=20)),
                ('p_option_parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_child', to='productapp.productoptionparent', verbose_name='p_option_parent_id')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_detail_image', models.ImageField(upload_to='ProductDetailImages')),
                ('p_target_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail_images', to='productapp.product', verbose_name='p_target_product_id')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('category_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productapp.productcategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category', to='productapp.productcategory', verbose_name='product_category'),
        ),
    ]
