# Generated by Django 3.1.4 on 2021-01-07 09:36

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('product_code', models.CharField(max_length=10, unique=True)),
                ('product_sale_id', models.CharField(max_length=10, unique=True)),
                ('product_title', models.CharField(max_length=100)),
                ('product_origin_price', models.IntegerField()),
                ('product_sale_price', models.IntegerField()),
                ('product_description', models.CharField(max_length=200)),
                ('product_is_display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductThumbnailImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_thumbnail', imagekit.models.fields.ProcessedImageField(upload_to='product_thumbnails')),
                ('p_target_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_thumbnails', to='productapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOptionParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_option_parent_title', models.CharField(max_length=20)),
                ('p_target_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='productapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOptionChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_option_child_title', models.CharField(max_length=20)),
                ('p_option_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_child', to='productapp.productoptionparent')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetailImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_detail_image', models.ImageField(upload_to='ProductDetailImages')),
                ('p_target_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail_images', to='productapp.product')),
            ],
        ),
    ]
