# Generated by Django 3.1.4 on 2021-01-19 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_product_option_class_1', models.CharField(max_length=30)),
                ('p_product_option_class_2', models.CharField(max_length=200)),
                ('p_target_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_option', to='productapp.product', verbose_name='p_target_product_id')),
            ],
        ),
        migrations.RemoveField(
            model_name='productoptionparent',
            name='p_target_product_id',
        ),
        migrations.DeleteModel(
            name='ProductOptionChild',
        ),
        migrations.DeleteModel(
            name='ProductOptionParent',
        ),
    ]
