# Generated by Django 3.1.4 on 2021-01-08 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_auto_20210108_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoptionchild',
            name='p_option_parent',
        ),
        migrations.RemoveField(
            model_name='productoptionparent',
            name='p_option_parent_title',
        ),
        migrations.AddField(
            model_name='productoptionchild',
            name='p_option_parent_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='product_child', to='productapp.productoptionparent', verbose_name='p_option_parent_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category', to='productapp.productcategory', verbose_name='product_category'),
        ),
        migrations.AlterField(
            model_name='productdetailimages',
            name='p_target_product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail_images', to='productapp.product', verbose_name='p_target_product_id'),
        ),
        migrations.AlterField(
            model_name='productoptionparent',
            name='p_target_product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='productapp.product', verbose_name='p_target_product_id'),
        ),
        migrations.AlterField(
            model_name='productthumbnailimages',
            name='p_target_product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_thumbnails', to='productapp.product', verbose_name='p_target_product_id'),
        ),
    ]
