# Generated by Django 3.1.4 on 2021-02-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_auto_20210208_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='category_parent',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
