# Generated by Django 3.1.4 on 2021-02-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_auto_20210217_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category_code',
            field=models.IntegerField(unique=True),
        ),
    ]
