# Generated by Django 3.1.4 on 2021-01-10 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0006_auto_20210110_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, default='신규 등록', null=True, on_delete=django.db.models.deletion.SET_NULL, to='productapp.productcategory'),
        ),
    ]
