# Generated by Django 3.1.4 on 2021-02-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0007_auto_20210220_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_origin_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sale_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
