# Generated by Django 3.1.4 on 2021-01-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0008_auto_20210110_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='parent_category',
            new_name='category_parent',
        ),
    ]
