# Generated by Django 3.1.4 on 2021-01-27 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_auto_20210124_1438'),
        ('cartapp', '0007_auto_20210127_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='productapp.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product_option', to='productapp.productoption'),
        ),
    ]
