# Generated by Django 3.1.4 on 2021-02-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0005_delete_ordertransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
