# Generated by Django 3.1.4 on 2021-02-02 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_auto_20210124_1438'),
        ('orderapp', '0006_remove_order_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='order',
            name='merchant_uid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='orderapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='productapp.product')),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product_option', to='productapp.productoption')),
            ],
        ),
    ]
