# Generated by Django 3.1.4 on 2021-02-03 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0008_auto_20210203_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imp_uid', models.CharField(max_length=100)),
                ('merchant_uid', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('paid_at', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('cancel_amount', models.IntegerField()),
                ('cancel_history', models.CharField(max_length=100)),
                ('cancel_reason', models.CharField(max_length=100)),
                ('cancelled_at', models.CharField(max_length=100)),
                ('fail_reason', models.CharField(max_length=100)),
                ('failed_at', models.CharField(max_length=100)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_transaction', to='orderapp.order')),
            ],
        ),
    ]
