# Generated by Django 3.1.4 on 2021-02-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0009_ordertransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertransaction',
            name='cancel_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='cancel_history',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='cancelled_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='fail_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='failed_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='paid_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
