# Generated by Django 3.1.4 on 2021-02-03 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0011_ordertransaction_validation_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertransaction',
            name='validation_check',
        ),
    ]
