# Generated by Django 3.1.4 on 2021-02-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0012_remove_ordertransaction_validation_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransaction',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
