# Generated by Django 3.1.4 on 2021-02-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0013_ordertransaction_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_option',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_option_1',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_option_2',
            field=models.CharField(default='temp', max_length=20),
            preserve_default=False,
        ),
    ]
