# Generated by Django 3.1.4 on 2021-02-08 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0014_auto_20210206_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_option_1',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_option_2',
        ),
    ]
