# Generated by Django 3.1.4 on 2021-02-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0016_auto_20210208_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertransaction',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
